os:
  - linux
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - MAVEN_USER_HOME=$HOME/.m2/repository/
before_install:
  - |
    echo '*** Using OpenJDK 17 by default'
    sudo apt-get update -q
    sudo apt-get install -y openjdk-17-jdk
    sudo update-java-alternatives -s java-1.17.0-openjdk-amd64
    java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
script:
  - curl -Lo ./snyk $(curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url.*snyk-linux" | cut -d ':' -f 2,3 | tr -d \" | tr -d ' ')
  - chmod +x snyk
  - ./snyk test --all-projects || true
  - ./snyk monitor --all-projects
  - chmod +x mvnw
  - ./mvnw -ntp package
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./mvnw -ntp org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi

notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
