services:
  mybatis-demo:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mybatis-demo
      - SPRING_DATASOURCE_PASSWORD=P4ssword!
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
