version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
            - v1-dependencies-
      - run:
          name: Print Java Version
          command: "java -version"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Give Executable Power
          command: "chmod +x mvnw"
      - run:
          name: Backend tests
          command: ./mvnw clean compile

